workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

stages:
  - lint
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1024m"

before_script:
  - chmod +x gradlew

lint:
  stage: lint
  image: gradle:8.5-jdk21
  script:
    - ./gradlew checkstyleMain checkstyleTest spotbugsMain spotbugsTest --no-daemon
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
      - build/reports/spotbugs
    reports:
      codequality: build/reports/spotbugs/main.xml

test:
  stage: test
  image: gradle:8.5-jdk21
  script:
    - ./gradlew test --no-daemon
  artifacts:
    when: always
    paths:
      - build/test-results/test
      - build/reports/tests/test
    reports:
      junit: build/test-results/test/TEST-*.xml

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - build/

deploy:
  stage: deploy
  script:
    - echo "Deploy step"
  only:
    - main