workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1024m"

before_script:
  - chmod +x gradlew

build:
  stage: build
  image: gradle:8.5-jdk21
  script:
    - ./gradlew clean build checkstyleMain checkstyleTest --no-daemon -x test
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
