server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active: dev

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway, bank-gateway
          routes:
            - id: account-service
              uri: http://account-service:8080
              predicates:
                        - Path=/api/accounts/**
            - id: security-service
              uri: http://security-service:8080
              predicates:
                        - Path=/api/security/**
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080