server:
  port: 8080

spring:
  application:
    name: bank-app

  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    urls:
      - name: account-service
        url: http://localhost:8084/v3/api-docs
      - name: settings-service
        url: http://localhost:8082/v3/api-docs
      - name: security-service
        url: http://localhost:8085/v3/api-docs