server:
  port: 8080

spring:
  application:
    name: kyc-service
  jackson:
    time-zone: UTC
  # PostgreSQL Database Settings
  datasource:
    url: jdbc:postgresql://kyc-service_postgres:5432/kyc_verifications
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: kyc-documents
  auto-create-bucket: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
