spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mainDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080
    - http://localhost:8081

logging:
  level:
    org.springframework.security: DEBUG