server:
  port: 8080

spring:
  application:
    name: account-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/mainDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,kafka
        liveness:
          include: ping

kyc-service:
  url: ${KYC_SERVICE_URL:http://kyc-service:8080}