spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mainDB
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

cors:
  allowed-origins:
    - https://app.bank.example.com
    - https://dashboard.bank.example.com

logging:
  level:
    root: INFO