server:
  port: 8080

spring:
  application:
    name: auth-statistics-service
  liquibase:
    enabled : false

  # Kafka
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: auth-statistics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # PostgreSQL Database Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/mainDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
